-- AlterTable
ALTER TABLE "Stroke" ADD COLUMN     "points" JSONB NOT NULL DEFAULT '[]',
ALTER COLUMN "prevX" DROP NOT NULL,
ALTER COLUMN "prevY" DROP NOT NULL,
ALTER COLUMN "x" DROP NOT NULL,
ALTER COLUMN "y" DROP NOT NULL;
